import os
from modules import common
from modules.common import v,vv,vvv
import json

"""
DATA STORAGE CLASSES USED THROUGHOUT THE PROJECT
"""

#--------------------------------------------------------------------------------------------------------------------------------

class Dirlist(object):
	"""
	contains "data" - list of registered {"directory":<directorystring>, "files":[file1, file2..], "search_place:<searched_dir>"}
	dicts. provides operations over the data
	is generated by functions of actions.py
	"""
	def __init__(self, data=None, username=None, verbose=None):
		""" initializer """
		self.data = data # list of registered data dicts
		self.username = username # username used during search
		self.verbose = verbose # verboseness level

	def export_json(self, name):
		"""
		exports the structure to a .json file
		True on success, False on bad
		"""
		if (vv(self.verbose)):
			print("\n--- exporting dirlist to",name,"\n")
		try:
			fname = os.path.join(os.path.join(os.getcwd(), "exports/dirlist_dump"), name+".json")
		except Exception as e:
			print("[x] Could not write to destination ["+fname+"], check if the folders exist")
			return False
	
		common.str_to_file(fname, json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4), self.verbose)

		if (v(self.verbose)):
			print(".json master export OK, wrote to "+fname)
		return True

	def import_json(self, name, location="datasource/dirlist_dump"):
		"""
		imports to the structure from a .json file
		True on success, False on bad
		"""
		if (vvv(self.verbose)):
			print("\n--- loading to dirlist from",name,"\n")
		fname = os.path.join(os.path.join(os.getcwd(), location), name)
		if not os.path.isfile(fname):
			if v(self.verbose):
				print("[!] IMPORT FAILELD: no file "+fname)
			return False
		fh = open(fname, "r")
		text = fh.read()
		stuff = json.loads(text)
		fh.close()
		try:
			self.data = stuff["data"]
			self.username = stuff["username"]
		except Exception as e:
			print("[x] IMPORT FAILELD: one or more data fields missing in "+fname)
			return False
		if (vvv(self.verbose)):
			print(".json master import from "+fname+" OK")
		return True

#--------------------------------------------------------------------------------------------------------------------------------
